In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
col_10_path = "County_data/Missouri_county_2010.csv"
col_10 = pd.read_csv(col_10_path)
col_10 = col_10[['County','Violent crime']]
col_10.head()

      County  Violent crime
0     Andrew            3.0
1      Bates           18.0
2  Bollinger            3.0
3      Boone          116.0
4   Buchanan           24.0

In [3]:
col_11_path = "County_data/Missouri_county_2011.csv"
col_11 = pd.read_csv(col_11_path)
col_11 = col_11[['County','Violent crime']]
col_11.head()

      County  Violent crime
0     Andrew            2.0
1      Bates           31.0
2  Bollinger           14.0
3      Boone           90.0
4   Buchanan           22.0

In [4]:
file_path = "County_data/Missouri_county_2012.csv"
col_12 = pd.read_csv(file_path)
col_12 = col_12[['County','Violent crime']]
col_12.head()

      County  Violent crime
0     Andrew            5.0
1      Bates           33.0
2  Bollinger           12.0
3      Boone          114.0
4   Buchanan           20.0

In [5]:
file_path = "County_data/Missouri_county_2013.csv"
col_13 = pd.read_csv(file_path)
col_13 = col_13[['County','Violent crime']]
col_13.head()

      County  Violent crime
0     Andrew           14.0
1      Bates           74.0
2  Bollinger           33.0
3      Boone          111.0
4   Buchanan           21.0

In [6]:
file_path = "County_data/Missouri_county_2014.csv"
col_14 = pd.read_csv(file_path)
col_14 = col_14[['County','Violent crime']]
col_14.head()

      County  Violent crime
0     Andrew           18.0
1      Bates           63.0
2  Bollinger           12.0
3      Boone          131.0
4   Buchanan           19.0

In [7]:
file_path = "County_data/Missouri_county_2015.csv"
col_15 = pd.read_csv(file_path)
col_15 = col_15[['County','Violent crime']]
col_15.head()

      County  Violent crime
0     Andrew           13.0
1      Bates           50.0
2  Bollinger           46.0
3      Boone          126.0
4   Buchanan           28.0

In [8]:
file_path = "County_data/Missouri_county_2016.csv"
col_16 = pd.read_csv(file_path)
col_16 = col_16[['County','Violent crime']]
col_16.head()

      County  Violent crime
0     Andrew           33.0
1      Bates           50.0
2  Bollinger           87.0
3      Boone          125.0
4   Buchanan           28.0

In [9]:
result_1 = pd.merge(col_10, col_11, how='left', on=['County'])
result_1 = result_1.rename(columns={'Violent crime_x':'2010','Violent crime_y':'2011'})
result_1

             County   2010   2011
0            Andrew    3.0    2.0
1             Bates   18.0   31.0
2         Bollinger    3.0   14.0
3             Boone  116.0   90.0
4          Buchanan   24.0   22.0
5          Caldwell   30.0   17.0
6          Callaway   71.0   60.0
7    Cape Girardeau  135.0   13.0
8              Cass   41.0   48.0
9         Christian  145.0   66.0
10             Clay   31.0   25.0
11          Clinton   22.0   49.0
12             Cole   45.0   48.0
13           Dallas   23.0   30.0
14          De Kalb    6.0    8.0
15         Franklin   70.0   89.0
16           Greene  129.0   96.0
17          Jackson   77.0   42.0
18           Jasper  184.0  152.0
19        Jefferson  406.0  384.0
20        Lafayette   18.0   10.0
21          Lincoln   90.0   89.0
22         McDonald   51.0   93.0
23         Moniteau   14.0    5.0
24           Newton  101.0   40.0
25            Osage   19.0   39.0
26           Platte   29.0   53.0
27             Polk   83.0   88.0
28              Ray   18.0   19.0
29      St. Charles  157.0  141.0
..              ...    ...    ...
79       New Madrid   17.0   20.0
80          Nodaway    5.0   36.0
81           Oregon   17.0    9.0
82            Ozark   21.0   12.0
83         Pemiscot   19.0   29.0
84            Perry   11.0    6.0
85           Pettis   21.0    9.0
86           Phelps   50.0   41.0
87             Pike   25.0   23.0
88          Pulaski   66.0   91.0
89            Ralls    8.0    5.0
90         Randolph    7.0    6.0
91         Reynolds   11.0   28.0
92           Ripley   19.0   29.0
93         Scotland    1.0    NaN
94            Scott   23.0   24.0
95          Shannon   14.0    3.0
96           Shelby    0.0    2.0
97        St. Clair   11.0    6.0
98   Ste. Genevieve   33.0   59.0
99     St. Francois   75.0   81.0
100        Stoddard   29.0   25.0
101           Stone   79.0   80.0
102        Sullivan   14.0   10.0
103           Taney   96.0  117.0
104           Texas    7.0    6.0
105          Vernon   27.0   33.0
106           Wayne    6.0   10.0
107           Worth    8.0    2.0
108          Wright   15.0   16.0

[109 rows x 3 columns]

In [10]:
result_2 = pd.merge(result_1, col_12, how='left', on=['County'])
result_2

             County   2010   2011  Violent crime
0            Andrew    3.0    2.0            5.0
1             Bates   18.0   31.0           33.0
2         Bollinger    3.0   14.0           12.0
3             Boone  116.0   90.0          114.0
4          Buchanan   24.0   22.0           20.0
5          Caldwell   30.0   17.0           29.0
6          Callaway   71.0   60.0           53.0
7    Cape Girardeau  135.0   13.0            9.0
8              Cass   41.0   48.0           46.0
9         Christian  145.0   66.0           55.0
10             Clay   31.0   25.0           36.0
11          Clinton   22.0   49.0           22.0
12             Cole   45.0   48.0           55.0
13           Dallas   23.0   30.0            NaN
14          De Kalb    6.0    8.0            7.0
15         Franklin   70.0   89.0           50.0
16           Greene  129.0   96.0           88.0
17          Jackson   77.0   42.0           56.0
18           Jasper  184.0  152.0          172.0
19        Jefferson  406.0  384.0          303.0
20        Lafayette   18.0   10.0           12.0
21          Lincoln   90.0   89.0           57.0
22         McDonald   51.0   93.0          122.0
23         Moniteau   14.0    5.0           10.0
24           Newton  101.0   40.0           74.0
25            Osage   19.0   39.0            5.0
26           Platte   29.0   53.0           55.0
27             Polk   83.0   88.0           78.0
28              Ray   18.0   19.0           37.0
29      St. Charles  157.0  141.0          142.0
..              ...    ...    ...            ...
79       New Madrid   17.0   20.0           22.0
80          Nodaway    5.0   36.0           13.0
81           Oregon   17.0    9.0           22.0
82            Ozark   21.0   12.0           30.0
83         Pemiscot   19.0   29.0           15.0
84            Perry   11.0    6.0           12.0
85           Pettis   21.0    9.0           16.0
86           Phelps   50.0   41.0           49.0
87             Pike   25.0   23.0            9.0
88          Pulaski   66.0   91.0          154.0
89            Ralls    8.0    5.0            6.0
90         Randolph    7.0    6.0            9.0
91         Reynolds   11.0   28.0           22.0
92           Ripley   19.0   29.0           27.0
93         Scotland    1.0    NaN            3.0
94            Scott   23.0   24.0           17.0
95          Shannon   14.0    3.0           10.0
96           Shelby    0.0    2.0            5.0
97        St. Clair   11.0    6.0            9.0
98   Ste. Genevieve   33.0   59.0           49.0
99     St. Francois   75.0   81.0           76.0
100        Stoddard   29.0   25.0           21.0
101           Stone   79.0   80.0          121.0
102        Sullivan   14.0   10.0            8.0
103           Taney   96.0  117.0           83.0
104           Texas    7.0    6.0           13.0
105          Vernon   27.0   33.0           37.0
106           Wayne    6.0   10.0            9.0
107           Worth    8.0    2.0            2.0
108          Wright   15.0   16.0            5.0

[109 rows x 4 columns]

In [11]:
result_3 = pd.merge(result_2, col_13, how='left', on=['County'])
result_3 = result_3.rename(columns={'Violent crime_x':'2012','Violent crime_y':'2013'})
result_3

             County   2010   2011   2012   2013
0            Andrew    3.0    2.0    5.0   14.0
1             Bates   18.0   31.0   33.0   74.0
2         Bollinger    3.0   14.0   12.0   33.0
3             Boone  116.0   90.0  114.0  111.0
4          Buchanan   24.0   22.0   20.0   21.0
5          Caldwell   30.0   17.0   29.0   23.0
6          Callaway   71.0   60.0   53.0   76.0
7    Cape Girardeau  135.0   13.0    9.0   20.0
8              Cass   41.0   48.0   46.0   29.0
9         Christian  145.0   66.0   55.0   51.0
10             Clay   31.0   25.0   36.0   13.0
11          Clinton   22.0   49.0   22.0   20.0
12             Cole   45.0   48.0   55.0   63.0
13           Dallas   23.0   30.0    NaN   33.0
14          De Kalb    6.0    8.0    7.0   10.0
15         Franklin   70.0   89.0   50.0   83.0
16           Greene  129.0   96.0   88.0   74.0
17          Jackson   77.0   42.0   56.0   37.0
18           Jasper  184.0  152.0  172.0  113.0
19        Jefferson  406.0  384.0  303.0  293.0
20        Lafayette   18.0   10.0   12.0    8.0
21          Lincoln   90.0   89.0   57.0   40.0
22         McDonald   51.0   93.0  122.0  142.0
23         Moniteau   14.0    5.0   10.0   17.0
24           Newton  101.0   40.0   74.0   38.0
25            Osage   19.0   39.0    5.0    4.0
26           Platte   29.0   53.0   55.0   43.0
27             Polk   83.0   88.0   78.0   61.0
28              Ray   18.0   19.0   37.0   39.0
29      St. Charles  157.0  141.0  142.0  118.0
..              ...    ...    ...    ...    ...
79       New Madrid   17.0   20.0   22.0   14.0
80          Nodaway    5.0   36.0   13.0   21.0
81           Oregon   17.0    9.0   22.0   15.0
82            Ozark   21.0   12.0   30.0   39.0
83         Pemiscot   19.0   29.0   15.0   15.0
84            Perry   11.0    6.0   12.0   17.0
85           Pettis   21.0    9.0   16.0   18.0
86           Phelps   50.0   41.0   49.0   72.0
87             Pike   25.0   23.0    9.0   10.0
88          Pulaski   66.0   91.0  154.0   76.0
89            Ralls    8.0    5.0    6.0    7.0
90         Randolph    7.0    6.0    9.0    9.0
91         Reynolds   11.0   28.0   22.0   15.0
92           Ripley   19.0   29.0   27.0   15.0
93         Scotland    1.0    NaN    3.0    0.0
94            Scott   23.0   24.0   17.0   32.0
95          Shannon   14.0    3.0   10.0   11.0
96           Shelby    0.0    2.0    5.0    3.0
97        St. Clair   11.0    6.0    9.0   19.0
98   Ste. Genevieve   33.0   59.0   49.0   25.0
99     St. Francois   75.0   81.0   76.0   44.0
100        Stoddard   29.0   25.0   21.0   23.0
101           Stone   79.0   80.0  121.0  124.0
102        Sullivan   14.0   10.0    8.0   14.0
103           Taney   96.0  117.0   83.0   88.0
104           Texas    7.0    6.0   13.0   25.0
105          Vernon   27.0   33.0   37.0   40.0
106           Wayne    6.0   10.0    9.0   23.0
107           Worth    8.0    2.0    2.0    0.0
108          Wright   15.0   16.0    5.0   10.0

[109 rows x 5 columns]

In [12]:
result_4 = pd.merge(result_3, col_14, how='left', on=['County'])
result_4 = result_4.dropna()
result_4

,County,2010,2011,2012,2013,Violent crime
0,Andrew,3.0,2.0,5.0,14.0,18.0
1,Bates,18.0,31.0,33.0,74.0,63.0
2,Bollinger,3.0,14.0,12.0,33.0,12.0
3,Boone,116.0,90.0,114.0,111.0,131.0
4,Buchanan,24.0,22.0,20.0,21.0,19.0
5,Caldwell,30.0,17.0,29.0,23.0,9.0
6,Callaway,71.0,60.0,53.0,76.0,97.0
7,Cape Girardeau,135.0,13.0,9.0,20.0,20.0
8,Cass,41.0,48.0,46.0,29.0,26.0
9,Christian,145.0,66.0,55.0,51.0,37.0
10,Clay,31.0,25.0,36.0,13.0,54.0
11,Clinton,22.0,49.0,22.0,20.0,69.0
12,Cole,45.0,48.0,55.0,63.0,30.0
14,De Kalb,6.0,8.0,7.0,10.0,13.0
15,Franklin,70.0,89.0,50.0,83.0,81.0
16,Greene,129.0,96.0,88.0,74.0,44.0
17,Jackson,77.0,42.0,56.0,37.0,54.0
18,Jasper,184.0,152.0,172.0,113.0,187.0
19,Jefferson,406.0,384.0,303.0,293.0,320.0
20,Lafayette,18.0,10.0,12.0,8.0,14.0
21,Lincoln,90.0,89.0,57.0,40.0,71.0
22,McDonald,51.0,93.0,122.0,142.0,111.0
23,Moniteau,14.0,5.0,10.0,17.0,17.0
24,Newton,101.0,40.0,74.0,38.0,25.0
25,Osage,19.0,39.0,5.0,4.0,9.0
26,Platte,29.0,53.0,55.0,43.0,33.0
27,Polk,83.0,88.0,78.0,61.0,53.0
28,Ray,18.0,19.0,37.0,39.0,41.0
29,St. Charles,157.0,141.0,142.0,118.0,125.0
30,St. Louis County Police Department,1090.0,1043.0,1003.0,1043.0,1321.0
...,...,...,...,...,...,...
78,Morgan,34.0,45.0,97.0,36.0,19.0
79,New Madrid,17.0,20.0,22.0,14.0,11.0
80,Nodaway,5.0,36.0,13.0,21.0,8.0
81,Oregon,17.0,9.0,22.0,15.0,10.0
82,Ozark,21.0,12.0,30.0,39.0,12.0
83,Pemiscot,19.0,29.0,15.0,15.0,7.0
84,Perry,11.0,6.0,12.0,17.0,19.0
85,Pettis,21.0,9.0,16.0,18.0,20.0
86,Phelps,50.0,41.0,49.0,72.0,67.0
87,Pike,25.0,23.0,9.0,10.0,9.0
88,Pulaski,66.0,91.0,154.0,76.0,70.0
89,Ralls,8.0,5.0,6.0,7.0,6.0
90,Randolph,7.0,6.0,9.0,9.0,6.0
91,Reynolds,11.0,28.0,22.0,15.0,14.0
92,Ripley,19.0,29.0,27.0,15.0,14.0
94,Scott,23.0,24.0,17.0,32.0,126.0
95,Shannon,14.0,3.0,10.0,11.0,9.0
96,Shelby,0.0,2.0,5.0,3.0,1.0
97,St. Clair,11.0,6.0,9.0,19.0,28.0
98,Ste. Genevieve,33.0,59.0,49.0,25.0,47.0
99,St. Francois,75.0,81.0,76.0,44.0,56.0
100,Stoddard,29.0,25.0,21.0,23.0,20.0
101,Stone,79.0,80.0,121.0,124.0,132.0
102,Sullivan,14.0,10.0,8.0,14.0,8.0
103,Taney,96.0,117.0,83.0,88.0,82.0
104,Texas,7.0,6.0,13.0,25.0,17.0
105,Vernon,27.0,33.0,37.0,40.0,52.0
106,Wayne,6.0,10.0,9.0,23.0,27.0
107,Worth,8.0,2.0,2.0,0.0,2.0
108,Wright,15.0,16.0,5.0,10.0,27.0

In [13]:
result_5 = pd.merge(result_4, col_15, how='left', on=['County'])
result_5

,County,2010,2011,2012,2013,Violent crime_x,Violent crime_y
0,Andrew,3.0,2.0,5.0,14.0,18.0,13.0
1,Bates,18.0,31.0,33.0,74.0,63.0,50.0
2,Bollinger,3.0,14.0,12.0,33.0,12.0,46.0
3,Boone,116.0,90.0,114.0,111.0,131.0,126.0
4,Buchanan,24.0,22.0,20.0,21.0,19.0,28.0
5,Caldwell,30.0,17.0,29.0,23.0,9.0,19.0
6,Callaway,71.0,60.0,53.0,76.0,97.0,105.0
7,Cape Girardeau,135.0,13.0,9.0,20.0,20.0,41.0
8,Cass,41.0,48.0,46.0,29.0,26.0,55.0
9,Christian,145.0,66.0,55.0,51.0,37.0,102.0
10,Clay,31.0,25.0,36.0,13.0,54.0,32.0
11,Clinton,22.0,49.0,22.0,20.0,69.0,51.0
12,Cole,45.0,48.0,55.0,63.0,30.0,28.0
13,De Kalb,6.0,8.0,7.0,10.0,13.0,NaN
14,Franklin,70.0,89.0,50.0,83.0,81.0,67.0
15,Greene,129.0,96.0,88.0,74.0,44.0,55.0
16,Jackson,77.0,42.0,56.0,37.0,54.0,47.0
17,Jasper,184.0,152.0,172.0,113.0,187.0,125.0
18,Jefferson,406.0,384.0,303.0,293.0,320.0,555.0
19,Lafayette,18.0,10.0,12.0,8.0,14.0,12.0
20,Lincoln,90.0,89.0,57.0,40.0,71.0,92.0
21,McDonald,51.0,93.0,122.0,142.0,111.0,90.0
22,Moniteau,14.0,5.0,10.0,17.0,17.0,10.0
23,Newton,101.0,40.0,74.0,38.0,25.0,41.0
24,Osage,19.0,39.0,5.0,4.0,9.0,3.0
25,Platte,29.0,53.0,55.0,43.0,33.0,19.0
26,Polk,83.0,88.0,78.0,61.0,53.0,60.0
27,Ray,18.0,19.0,37.0,39.0,41.0,30.0
28,St. Charles,157.0,141.0,142.0,118.0,125.0,NaN
29,St. Louis County Police Department,1090.0,1043.0,1003.0,1043.0,1321.0,1533.0
...,...,...,...,...,...,...,...
73,Morgan,34.0,45.0,97.0,36.0,19.0,32.0
74,New Madrid,17.0,20.0,22.0,14.0,11.0,6.0
75,Nodaway,5.0,36.0,13.0,21.0,8.0,6.0
76,Oregon,17.0,9.0,22.0,15.0,10.0,11.0
77,Ozark,21.0,12.0,30.0,39.0,12.0,19.0
78,Pemiscot,19.0,29.0,15.0,15.0,7.0,21.0
79,Perry,11.0,6.0,12.0,17.0,19.0,29.0
80,Pettis,21.0,9.0,16.0,18.0,20.0,23.0
81,Phelps,50.0,41.0,49.0,72.0,67.0,26.0
82,Pike,25.0,23.0,9.0,10.0,9.0,4.0
83,Pulaski,66.0,91.0,154.0,76.0,70.0,41.0
84,Ralls,8.0,5.0,6.0,7.0,6.0,6.0
85,Randolph,7.0,6.0,9.0,9.0,6.0,11.0
86,Reynolds,11.0,28.0,22.0,15.0,14.0,14.0
87,Ripley,19.0,29.0,27.0,15.0,14.0,10.0
88,Scott,23.0,24.0,17.0,32.0,126.0,NaN
89,Shannon,14.0,3.0,10.0,11.0,9.0,10.0
90,Shelby,0.0,2.0,5.0,3.0,1.0,4.0
91,St. Clair,11.0,6.0,9.0,19.0,28.0,13.0
92,Ste. Genevieve,33.0,59.0,49.0,25.0,47.0,31.0
93,St. Francois,75.0,81.0,76.0,44.0,56.0,60.0
94,Stoddard,29.0,25.0,21.0,23.0,20.0,24.0
95,Stone,79.0,80.0,121.0,124.0,132.0,113.0
96,Sullivan,14.0,10.0,8.0,14.0,8.0,9.0
97,Taney,96.0,117.0,83.0,88.0,82.0,112.0
98,Texas,7.0,6.0,13.0,25.0,17.0,25.0
99,Vernon,27.0,33.0,37.0,40.0,52.0,81.0
100,Wayne,6.0,10.0,9.0,23.0,27.0,56.0
101,Worth,8.0,2.0,2.0,0.0,2.0,2.0
102,Wright,15.0,16.0,5.0,10.0,27.0,21.0

In [14]:
result_6 = pd.merge(result_5, col_16, how='left', on=['County'])
result_6 = result_6.dropna()
result_6 = result_6.rename(columns={'Violent crime_x':'2014','Violent crime_y':'2015','Violent crime':'2016'})
result_6

,County,2010,2011,2012,2013,2014,2015,2016
0,Andrew,3.0,2.0,5.0,14.0,18.0,13.0,33.0
1,Bates,18.0,31.0,33.0,74.0,63.0,50.0,50.0
2,Bollinger,3.0,14.0,12.0,33.0,12.0,46.0,87.0
3,Boone,116.0,90.0,114.0,111.0,131.0,126.0,125.0
4,Buchanan,24.0,22.0,20.0,21.0,19.0,28.0,28.0
5,Caldwell,30.0,17.0,29.0,23.0,9.0,19.0,17.0
6,Callaway,71.0,60.0,53.0,76.0,97.0,105.0,117.0
7,Cape Girardeau,135.0,13.0,9.0,20.0,20.0,41.0,33.0
8,Cass,41.0,48.0,46.0,29.0,26.0,55.0,60.0
9,Christian,145.0,66.0,55.0,51.0,37.0,102.0,95.0
10,Clay,31.0,25.0,36.0,13.0,54.0,32.0,50.0
11,Clinton,22.0,49.0,22.0,20.0,69.0,51.0,24.0
12,Cole,45.0,48.0,55.0,63.0,30.0,28.0,42.0
14,Franklin,70.0,89.0,50.0,83.0,81.0,67.0,71.0
15,Greene,129.0,96.0,88.0,74.0,44.0,55.0,83.0
16,Jackson,77.0,42.0,56.0,37.0,54.0,47.0,85.0
17,Jasper,184.0,152.0,172.0,113.0,187.0,125.0,123.0
18,Jefferson,406.0,384.0,303.0,293.0,320.0,555.0,196.0
19,Lafayette,18.0,10.0,12.0,8.0,14.0,12.0,10.0
20,Lincoln,90.0,89.0,57.0,40.0,71.0,92.0,132.0
21,McDonald,51.0,93.0,122.0,142.0,111.0,90.0,101.0
22,Moniteau,14.0,5.0,10.0,17.0,17.0,10.0,1.0
24,Osage,19.0,39.0,5.0,4.0,9.0,3.0,3.0
25,Platte,29.0,53.0,55.0,43.0,33.0,19.0,41.0
26,Polk,83.0,88.0,78.0,61.0,53.0,60.0,50.0
27,Ray,18.0,19.0,37.0,39.0,41.0,30.0,102.0
29,St. Louis County Police Department,1090.0,1043.0,1003.0,1043.0,1321.0,1533.0,1784.0
30,Warren,42.0,67.0,43.0,65.0,70.0,91.0,68.0
31,Washington,40.0,35.0,39.0,43.0,66.0,51.0,106.0
32,Webster,19.0,12.0,14.0,21.0,26.0,41.0,11.0
...,...,...,...,...,...,...,...,...
71,Monroe,6.0,5.0,4.0,10.0,2.0,3.0,5.0
72,Montgomery,4.0,3.0,3.0,1.0,4.0,6.0,12.0
73,Morgan,34.0,45.0,97.0,36.0,19.0,32.0,36.0
75,Nodaway,5.0,36.0,13.0,21.0,8.0,6.0,7.0
76,Oregon,17.0,9.0,22.0,15.0,10.0,11.0,12.0
77,Ozark,21.0,12.0,30.0,39.0,12.0,19.0,15.0
78,Pemiscot,19.0,29.0,15.0,15.0,7.0,21.0,23.0
79,Perry,11.0,6.0,12.0,17.0,19.0,29.0,36.0
80,Pettis,21.0,9.0,16.0,18.0,20.0,23.0,29.0
81,Phelps,50.0,41.0,49.0,72.0,67.0,26.0,19.0
82,Pike,25.0,23.0,9.0,10.0,9.0,4.0,2.0
83,Pulaski,66.0,91.0,154.0,76.0,70.0,41.0,65.0
84,Ralls,8.0,5.0,6.0,7.0,6.0,6.0,19.0
85,Randolph,7.0,6.0,9.0,9.0,6.0,11.0,10.0
86,Reynolds,11.0,28.0,22.0,15.0,14.0,14.0,11.0
87,Ripley,19.0,29.0,27.0,15.0,14.0,10.0,15.0
89,Shannon,14.0,3.0,10.0,11.0,9.0,10.0,24.0
90,Shelby,0.0,2.0,5.0,3.0,1.0,4.0,3.0
91,St. Clair,11.0,6.0,9.0,19.0,28.0,13.0,22.0
92,Ste. Genevieve,33.0,59.0,49.0,25.0,47.0,31.0,31.0
93,St. Francois,75.0,81.0,76.0,44.0,56.0,60.0,70.0
94,Stoddard,29.0,25.0,21.0,23.0,20.0,24.0,15.0
95,Stone,79.0,80.0,121.0,124.0,132.0,113.0,130.0
96,Sullivan,14.0,10.0,8.0,14.0,8.0,9.0,9.0
97,Taney,96.0,117.0,83.0,88.0,82.0,112.0,93.0
98,Texas,7.0,6.0,13.0,25.0,17.0,25.0,21.0
99,Vernon,27.0,33.0,37.0,40.0,52.0,81.0,68.0
100,Wayne,6.0,10.0,9.0,23.0,27.0,56.0,20.0
101,Worth,8.0,2.0,2.0,0.0,2.0,2.0,1.0
102,Wright,15.0,16.0,5.0,10.0,27.0,21.0,26.0

In [15]:
sum_2010 = result_6['2010'].sum()
sum_2011 = result_6['2011'].sum()
sum_2012 = result_6['2012'].sum()
sum_2013 = result_6['2013'].sum()
sum_2014 = result_6['2014'].sum()
sum_2015 = result_6['2015'].sum()
sum_2016 = result_6['2016'].sum()
sum_all = [sum_2010, sum_2011, sum_2012, sum_2013, sum_2014, sum_2015, sum_2016]

In [17]:
#x values for the chart
x_vals = ['2010','2011','2012','2013','2014','2015','2016']

plt.plot(x_vals, sum_all)
sns.set_style("darkgrid")
plt.savefig("Missouri_Crime_2010_2016")